name: Coverage Diff Comment

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write # Required to push coverage data to a special branch
  pull-requests: write # Required to comment on pull requests

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt

      - name: Run tests and generate coverage report
        run: pytest --cov=./ --cov-report=xml

      - name: Python Coverage Comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          COVERAGE_DATA_BRANCH: python-coverage-comment-action-data

      - name: Enforce coverage
        if: ${{ steps.coverage_comment.outputs.new_percent_covered < steps.coverage_comment.outputs.reference_percent_covered }}
        run: echo "Coverage decreased." && exit 1